ait_ilcdmp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    # Examples:
    # url(r'^$', 'ait_ilcdmp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include('info_system.urls.admin', namespace='admin')),
    url(r'^student/', include('info_system.urls.student', namespace='student')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += staticfiles_urlpatterns()

info_system/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from views import RegisterView
from views import StudentLoginView

urlpatterns = [
      
    url(r'^register/', RegisterView.as_view(), name="register"),
    url(r'^login/', StudentLoginView.as_view(), name="login"),

]

templates/activity_details.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="container">
<div class="page-title">Activity Details</div>
<hr>
	<div class="seminar-detail-page">
		<h4><b>Title:</b> {{object.title}}</h4>
		<p><b>Description:</b></p>
		<p class="seminar-detail-description">{{object.description}}</p>
		<div class="seminar-detail-info"><b>Date:</b> {{object.date}}</div>
		<div class="seminar-detail-info"><b>Time:</b> {{object.time}}</div>
		<div class= ""><b>School:</b> {%if seminar.school == 1%}SATES{% elif seminar.school == 2%}ABS{% else %}ASDASS{% endif %}</div>
          	{% if object.date > today.date or object.date == today.date and object.time > today.time %}
			<div class="seminar-edit-link text-nowrap">
					{% if object.seminar %}
				<a href="/admin/seminars/edit/{{object.seminar.pk}}">
					{% else %}
				<a href="/admin/seminars/edit/{{object.pk}}">
					{% endif %}
					Edit this Activity 
				</a>  
			</div>
		{% endif %}

	</div>
</div>
{% endblock %}
{% block footer %}
{% include 'admin_footer.html'%}
{% endblock %}

templates/activity_new.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="container">
<div class="page-title">Create New Activity</div>
	<div class="form-container">
	    <form class="" action="#" id="new-seminar-form" role="form" method="post">
		    {% csrf_token %}
		    <div class="row">
			<div class="form-group col-sm-12">
			    <label class="control-label" for="{{form.title.auto_id}}">
				    {{form.title.label}}
			    </label>
				    {% render_field form.title class+="form-control" %}
			</div>

		    </div>

		    <div class="">
			<div class="form-group">
			    <label class="control-label" for="{{form.description.auto_id}}">
				    {{form.description.label}}
			    </label>
				    {% render_field form.description class+="form-control" %}
			</div>
		    </div>

		    <div class="row">
			<div class="form-group col-md-6">
			    <label class="control-label" for="{{form.date.auto_id}}">
				    {{form.date.label}}
			    </label>
				    {% render_field form.date class+="form-control" %}
			</div>

			<div class="form-group col-md-6">
			    <label class="control-label" for="{{form.time.auto_id}}">
				    {{form.time.label}}
			    </label>
				    {% render_field form.time class+="form-control" %}
			</div>
		    </div>
		<div class="form-group">
	        <label class="control-label">School</label>
		<div class="radio-group row">
			<div class="col-sm-4 radio">
				<input class="custom-radio" type="radio"
				name="school" id="sates" value=1>
				<label class="radio-label" for="sates">
				SATES
				</label>
			</div>
			<div class="col-sm-4 radio">
				<input class="custom-radio" type="radio" 
				name="school" id="abs" value=2>
				<label class="radio-label" for="abs">
				ABS
				</label>
			</div>
			<div class="col-sm-4 radio">
				<input class="custom-radio" type="radio"
				name="school" id="asdass" value=3>
				<label class="radio-label" for="asdass">
				ASDASS
				</label>
			</div>
		</div>
		</div>
		<div class="form-group">
	            <label class="control-label">Target Groups</label>
	        <div class="row">
			<div class="col-sm-6">
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="all" value=0>
				<label class="check-label" for="all">All Students Enrolled</label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="new" value=1>
				<label class="check-label" for="new">Students Without SCADIIL points </label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="cdes-ufs" value=2>
				<label class="check-label" for="cdes-ufs">Students who have passed CDES or UFS or both</label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="pre-intern" value=3>
				<label class="check-label" for="pre-intern">Students who qualify to commence Internship </label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="at-post" value=4>
				<label class="check-label" for="at-post">Students at post on Internship </label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="returnee" value=5>
				<label class="check-label" for="returnee">Students returning from Internship</label>
		    </div></div>
		    <div class="col-sm-6">
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="pass-intern" value=6>
				<label class="check-label" for="pass-intern">Students who have passed Internship</label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="cap-prop" value=7>
				<label class="check-label" for="cap-prop">Students who qualify to start Capstone Project </label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="cap-one" value=8>
				<label class="check-label" for="cap-one">Students who qualify to do Capstone Part One</label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="cap-two" value=9>
				<label class="check-label" for="cap-two">Students who qualify to do Capstone Part Two</label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="cap-viva" value=10>
				<label class="check-label" for="cap-viva">Students who qualify to do Viva</label>
		    </div>
		    <div class="checkbox">
				<input class="custom-check" type="checkbox" name="targets[]" id="passed-viva" value=11>
				<label class="check-label" for="passed-viva">Students who have passed Viva</label>
		    </div></div>
		</div>
		</div>
		<div class="">
			<button type="submit" class="btn btn-primary right" id="">
				Create This Activity
			</button>  
		</div>
	    </form>
	</div>
</div>
{% endblock %}

{% block footer %}
{% include 'admin_footer.html'%}
{% endblock %}

templates/admin_login.html
{% extends "base.html"%}
{% load widget_tweaks %}

{% block contents %}
<div class="container">
    <div id="" class="form-container compact-login-form">
    {% if messages %}
        <div class="title">
	    {% for message in messages %}
	        {% if 'student_login_incorrect' in message.extra_tags %}
			<script>
			     student_login_error = true;
			</script>
		    <div class="alert alert-danger" id="">
			    <p class='server-message'> {{ message }} </p>
		    </div>
		{% endif %}
	        {% if 'admin_login_incorrect' in message.extra_tags %}
			<script>
			     admin_login_error = true;
			</script>
		    <div class="alert alert-danger" id="">
			    <p class='server-message'> {{ message }} </p>
		    </div>
		{% endif %}
	    {% endfor %}
        </div>
    {% endif %}
	    <form id="admin-login-form" action="" role="form" method="post">
		    {% csrf_token %}
                <div class="form-group">
			<label class="control-label" for="{{form.username.auto_id}}">
				{{form.username.label}}
			</label>
			        {% render_field form.username class+="form-control" %}
		</div>

		<div class="form-group">
			<label class="control-label" for="{{form.password.auto_id}}">
		        	{{form.password.label}}
			</label>
			        {% render_field form.password class+="form-control"%}
		</div>
		<div class="">
	                <button type="submit" class="btn btn-primary login-button">
		                Login
			</button> 
			<div class="forgot-password forgot-password-static">
				<a class="" href="{% url 'admin:password_reset_request' %}">Forgot Password?</a>
			</div>
			<input type="hidden" name="next" value="{{request.GET.next}}">
	    </form>


    </div>
</div>
{% endblock %}

templates/attendance_list.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="container">
	<div class="page-title grade-title">Review Seminar Attendance</div>
	<div class=grade-summary> total <span class="badge">{{total}}</span></div>
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>ID Number</th>
			</tr>

		</thead>
		<tbody>
			{% for key, value in attendance.items %}
			<tr>
			       <td>{{value.0}}</td>
			       <td>{{value.1}}</td>
		       </tr>
		       {% empty %}
		       <p>malformed attendance sheet</p>
		       {% endfor %}
		</tbody>
	</table>
		<div class="accept-grade upload">
			<a href="/admin/seminar/{{pk}}/attendance/upload/" class="btn btn-primary" id="">
				Accept and Save
			</a>  
		</div>
</div>
{% endblock %}

{% block footer %}
{% include 'admin_footer.html'%}
{% endblock %}

templates/capstone_part_two.html
{% extends "base.html"%}
{% load widget_tweaks %}

{% block contents %}
{% block search %}
{% endblock %}
<div id=sidebar-wrapper class="">
     <div class="bs-sidebar">
	  <ul id="sidebar" class="" style="min-width:255px">
	      <li><div class="menu-heading"><span class="fa fa-tachometer fa-fw"></span>
		      Overview</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:activities'%}">Activities 
						<span class="hot badge">{{upcoming_activities_count}}</span></a></li>
				<li><a href="{% url 'admin:messages'%}">Messages</a></li>
				<li><a href="{% url 'admin:statistics'%}">Statistics</a></li>
			</ul>
		      </div>
	      </li>
	      <li class="active">
		      <div class="menu-heading"><span class="fa fa-group fa-fw"></span>
		      Students</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:students-all'%}">All Enrolled Students</a></li>
				<li><a href="{% url 'admin:students-complete'%}">Completion List</a></li> </ul> </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-file fa-fw"></span>
		      Courses</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:courses-ufs'%}">Foundation Studies</a></li>
				<li><a href="{% url 'admin:courses-cdes'%}">Career Development</a></li>
			</ul>
		      </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-video-camera fa-fw"></span>
		      University  Seminars</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:seminars-all'%}">All Seminars</a></li>
				<li><a href="{% url 'admin:seminars-upcoming'%}">Upcoming Seminars</a></li>
				<li><a href="{% url 'admin:seminars-past'%}">Past Seminars</a></li>
			</ul>
		      </div>
	      </li>
	      <li class=""><div class="menu-heading"><span class="fa fa-briefcase fa-fw"></span>
		      Internship  Program</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:internship-pre-interns'%}">
						Pre-Internship Students</a></li>
				<li><a href="{% url 'admin:internship-at-post'%}">Students At Post</a></li>
				<li><a href="{% url 'admin:internship-returnee'%}">Returnee Interns</a></li>
				<li><a href="{% url 'admin:internship-complete'%}">Completion List</a></li>
			</ul>
		      </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-book fa-fw"></span>
		      Capstone Project</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:capstone-proposal'%}">
						Proposal Students</a></li>
				<li><a href="{% url 'admin:capstone-part-one'%}">Part One Students</a></li>
				<li class="active"><a href="{% url 'admin:capstone-part-two'%}">
						Part Two Students</a></li>
				<li><a href="{% url 'admin:capstone-viva'%}">Viva Students</a></li>
				<li><a href="{% url 'admin:capstone-complete'%}">Completion List</a></li>
			</ul>
		      </div>
	      </li>
	  </ul>
     </div>
</div>
    <div class="static-header">	
	<div class="section-title text-nowrap">Capstone Part Two</div>
	<div id="search-wrapper">
	    <div class="input-group" style="min-width:">
		    <input type="text" class="form-control search" placeholder="Search... ">
		    <span class="input-group-btn">
			<button class="btn btn-primary search-btn" type="button">
		              <span style="font-size: 1.5em" class="glyphicon glyphicon-search"></span>
			</button>
		    </span>
	    </div>
	    <div class="section-controls-wrapper text-no-wrap" style="min-width:980px">
		    <div class="pull-left" style="margin-left: -30px">	
			    <div id="student-count" class="section-item">
				    total <span class="badge">{{total}}</span>
			    </div>
			    <div id="sates-count" class="section-item">
				    sates <span class="badge">{{sates}}</span>
			    </div>
			    <div id="asdass-count" class="section-item">
				    asdass <span class="badge">{{asdass}}</span>
			    </div>
			    <div id="abs-count" class="section-item">
				    abs <span class="badge">{{abs}}</span>
			    </div>
		    </div>

		    <div class="pull-right">	
			    <div id="sort" class="section-item">
				<a href=""><span class="fa fa-sort"> </span> Sort By</a>
			    </div>
			    <div id="filter" class="section-item">
				<a href=""><span class="fa fa-filter"> </span> Filter</a>
			    </div>
			    <div id="export-excel" class="section-item">
				<a href=""><span class="fa fa-upload"> </span> Export </a>
			    </div>
		    </div>

	    </div>
	</div>
    </div>
<div class="contents-wrapper">
	<div class="main-contents">
		{% for student in object_list %}
		{% empty %}
		    <p>No student has gotten here yet!</p>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/capstone_proposal.html
{% extends "base.html"%}
{% load widget_tweaks %}

{% block contents %}
{% block search %}
{% endblock %}
<div id=sidebar-wrapper class="">
     <div class="bs-sidebar">
	  <ul id="sidebar" class="" style="min-width:255px">
	      <li><div class="menu-heading"><span class="fa fa-tachometer fa-fw"></span>
		      Overview</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:activities'%}">Activities 
						<span class="hot badge">{{upcoming_activities_count}}</span></a></li>
				<li><a href="{% url 'admin:messages'%}">Messages</a></li>
				<li><a href="{% url 'admin:statistics'%}">Statistics</a></li>
			</ul>
		      </div>
	      </li>
	      <li class="active">
		      <div class="menu-heading"><span class="fa fa-group fa-fw"></span>
		      Students</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:students-all'%}">All Enrolled Students</a></li>
				<li><a href="{% url 'admin:students-complete'%}">Completion List</a></li> </ul> </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-file fa-fw"></span>
		      Courses</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:courses-ufs'%}">Foundation Studies</a></li>
				<li><a href="{% url 'admin:courses-cdes'%}">Career Development</a></li>
			</ul>
		      </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-video-camera fa-fw"></span>
		      University  Seminars</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:seminars-all'%}">All Seminars</a></li>
				<li><a href="{% url 'admin:seminars-upcoming'%}">Upcoming Seminars</a></li>
				<li><a href="{% url 'admin:seminars-past'%}">Past Seminars</a></li>
			</ul>
		      </div>
	      </li>
	      <li class=""><div class="menu-heading"><span class="fa fa-briefcase fa-fw"></span>
		      Internship  Program</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:internship-pre-interns'%}">
						Pre-Internship Students</a></li>
				<li><a href="{% url 'admin:internship-at-post'%}">Students At Post</a></li>
				<li><a href="{% url 'admin:internship-returnee'%}">Returnee Interns</a></li>
				<li><a href="{% url 'admin:internship-complete'%}">Completion List</a></li>
			</ul>
		      </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-book fa-fw"></span>
		      Capstone Project</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li class="active"><a href="{% url 'admin:capstone-proposal'%}">
						Proposal Students</a></li>
				<li><a href="{% url 'admin:capstone-part-one'%}">Part One Students</a></li>
				<li><a href="{% url 'admin:capstone-part-two'%}">Part Two Students</a></li>
				<li><a href="{% url 'admin:capstone-viva'%}">Viva Students</a></li>
				<li><a href="{% url 'admin:capstone-complete'%}">Completion List</a></li>
			</ul>
		      </div>
	      </li>
	  </ul>
     </div>
</div>
    <div class="static-header">	
	<div class="section-title text-nowrap">Capstone Proposal List</div>
	<div id="search-wrapper">
	    <div class="input-group" style="min-width:">
		    <input type="text" class="form-control search" placeholder="Search... ">
		    <span class="input-group-btn">
			<button class="btn btn-primary search-btn" type="button">
		              <span style="font-size: 1.5em" class="glyphicon glyphicon-search"></span>
			</button>
		    </span>
	    </div>
	    <div class="section-controls-wrapper text-no-wrap" style="min-width:980px">
		    <div class="pull-left" style="margin-left: -30px">	
			    <div id="student-count" class="section-item">
				    total <span class="badge">{{total}}</span>
			    </div>
			    <div id="sates-count" class="section-item">
				    sates <span class="badge">{{sates}}</span>
			    </div>
			    <div id="asdass-count" class="section-item">
				    asdass <span class="badge">{{asdass}}</span>
			    </div>
			    <div id="abs-count" class="section-item">
				    abs <span class="badge">{{abs}}</span>
			    </div>
		    </div>

		    <div class="pull-right">	
			    <div id="sort" class="section-item">
				<a href=""><span class="fa fa-sort"> </span> Sort By</a>
			    </div>
			    <div id="filter" class="section-item">
				<a href=""><span class="fa fa-filter"> </span> Filter</a>
			    </div>
			    <div id="export-excel" class="section-item">
				<a href=""><span class="fa fa-upload"> </span> Export </a>
			    </div>
		    </div>

	    </div>
	</div>
    </div>
<div class="contents-wrapper">
	<div class="main-contents">
		{% for student in object_list %}
		{% empty %}
		    <p>No student has gotten here yet!</p>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/internship_at_post.html
{% extends "base.html"%}
{% load widget_tweaks %}

{% block contents %}
{% block search %}
{% endblock %}
<div id=sidebar-wrapper class="">
     <div class="bs-sidebar">
	  <ul id="sidebar" class="" style="min-width:255px">
	      <li><div class="menu-heading"><span class="fa fa-tachometer fa-fw"></span>
		      Overview</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:activities'%}">Activities 
						<span class="hot badge">{{upcoming_activities_count}}</span></a></li>
				<li><a href="{% url 'admin:messages'%}">Messages</a></li>
				<li><a href="{% url 'admin:statistics'%}">Statistics</a></li>
			</ul>
		      </div>
	      </li>
	      <li class="active">
		      <div class="menu-heading"><span class="fa fa-group fa-fw"></span>
		      Students</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:students-all'%}">All Enrolled Students</a></li>
				<li><a href="{% url 'admin:students-complete'%}">Completion List</a></li> </ul> </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-file fa-fw"></span>
		      Courses</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:courses-ufs'%}">Foundation Studies</a></li>
				<li><a href="{% url 'admin:courses-cdes'%}">Career Development</a></li>
			</ul>
		      </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-video-camera fa-fw"></span>
		      University  Seminars</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:seminars-all'%}">All Seminars</a></li>
				<li><a href="{% url 'admin:seminars-upcoming'%}">Upcoming Seminars</a></li>
				<li><a href="{% url 'admin:seminars-past'%}">Past Seminars</a></li>
			</ul>
		      </div>
	      </li>
	      <li class=""><div class="menu-heading"><span class="fa fa-briefcase fa-fw"></span>
		      Internship  Program</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:internship-pre-interns'%}">
						Pre-Internship Students</a></li>
				<li class="active"><a href="{% url 'admin:internship-at-post'%}">
						Students At Post</a></li>
				<li><a href="{% url 'admin:internship-returnee'%}">Returnee Interns</a></li>
				<li><a href="{% url 'admin:internship-complete'%}">Completion List</a></li>
			</ul>
		      </div>
	      </li>
	      <li><div class="menu-heading"><span class="fa fa-book fa-fw"></span>
		      Capstone Project</div>
		      <div class="submenu">
			<ul class="submenu-wrapper nav nav-pills nav-stacked">
				<li><a href="{% url 'admin:capstone-proposal'%}">
						Proposal Students</a></li>
				<li><a href="{% url 'admin:capstone-part-one'%}">Part One Students</a></li>
				<li><a href="{% url 'admin:capstone-part-two'%}">Part Two Students</a></li>
				<li><a href="{% url 'admin:capstone-viva'%}">Viva Students</a></li>
				<li><a href="{% url 'admin:capstone-complete'%}">Completion List</a></li>
			</ul>
		      </div>
	      </li>
	  </ul>
     </div>
</div>
    <div class="static-header">	
	<div class="section-title text-nowrap">Students At Post</div>
	<div id="search-wrapper">
	    <div class="input-group" style="min-width:">
		    <input type="text" class="form-control search" placeholder="Search... ">
		    <span class="input-group-btn">
			<button class="btn btn-primary search-btn" type="button">
		              <span style="font-size: 1.5em" class="glyphicon glyphicon-search"></span>
			</button>
		    </span>
	    </div>
	    <div class="section-controls-wrapper text-no-wrap" style="min-width:980px">
		    <div class="pull-left" style="margin-left: -30px">	
			    <div id="student-count" class="section-item">
				    total <span class="badge">{{total}}</span>
			    </div>
			    <div id="sates-count" class="section-item">
				    sates <span class="badge">{{sates}}</span>
			    </div>
			    <div id="asdass-count" class="section-item">
				    asdass <span class="badge">{{asdass}}</span>
			    </div>
			    <div id="abs-count" class="section-item">
				    abs <span class="badge">{{abs}}</span>
			    </div>
		    </div>

		    <div class="pull-right">	
			    <div id="add-student" class="section-item">
				<a href=""><span class="fa fa-user-plus"> </span> Enrol </a>
			    </div>
			    <div id="sort" class="section-item">
				<a href=""><span class="fa fa-sort"> </span> Sort By</a>
			    </div>
			    <div id="filter" class="section-item">
				<a href=""><span class="fa fa-filter"> </span> Filter</a>
			    </div>
			    <div id="export-excel" class="section-item">
				<a href=""><span class="fa fa-upload"> </span> Export </a>
			    </div>
		    </div>

	    </div>
	</div>
    </div>
<div class="contents-wrapper">
	<div class="main-contents">
		{% for student in object_list %}
		{% empty %}
		    <p>This list is empty!</p>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/student_login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="container" id="login-container">
    <div class="row">
    <div id="student-login-container" class="form-container col-md-6" >
    {% if messages %}
        <div class="title">
	    {% for message in messages %}
	        {% if 'student_login_incorrect' in message.extra_tags %}
			<script>
			     student_login_error = true;
			</script>
		    <div class="alert alert-danger" id="">
			    <p class='server-message'> {{ message }} </p>
		    </div>
		{% endif %}
	        {% if 'admin_login_incorrect' in message.extra_tags %}
			<script>
			     admin_login_error = true;
			</script>
		    <div class="alert alert-danger" id="">
			    <p class='server-message'> {{ message }} </p>
		    </div>
		{% endif %}
	    {% endfor %}
        </div>
    {% endif %}
	    <form class="" action="#" id="student-login-form" role="form" method="post">
		    {% csrf_token %}
                <div class="form-group">
			<label class="control-label" for="{{form.id_number.auto_id}}">
				{{form.id_number.label}}
			</label>
			        {% render_field form.id_number class+="form-control uppercase" %}
		</div>

		<div class="form-group">
			<label class="control-label" for="{{form.password.auto_id}}">
		        	{{form.password.label}}
			</label>
			        {% render_field form.password class+="form-control"%}
		</div>
		<div class="">
	                <button type="submit" class="btn btn-primary login-button">
		                Login to SCaDIIL	
			</button>
			<div class="forgot-password forgot-password-dynamic">
				<a class="pull-right" href='{% url 'student:password_reset_request' %}'>Forgot Password?
				</a>
			</div>
		</div>
			<input type="hidden" name="next" value="{{request.GET.next}}">
	    </form>
    </div>

    <div class="register col-md-6">
	    <div class="col-container">
		    <h1 class="no-margin-top" id="enrolled_yet">Not Yet Enrolled on SCADIIL?</h1>
		    <a class="btn-link" href='{% url 'student:register'%}'>
	        <button type="submit" class="btn btn-primary" id="register-button">
		    Get Enrolled Now! >>	
      	        </button>
		</a>
            </div>
    </div>
    </div>
</div>
{% endblock %}

{% block footer %}
<div class="footer">
    <div class="container">
    
    </div>

</div>
{% endblock %}